// Generated by gencpp from file robotis_controller_msgs/ControlTorque.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_CONTROLTORQUE_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_CONTROLTORQUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis_controller_msgs
{
template <class ContainerAllocator>
struct ControlTorque_
{
  typedef ControlTorque_<ContainerAllocator> Type;

  ControlTorque_()
    : name()
    , enable()  {
    }
  ControlTorque_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , enable(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _enable_type;
  _enable_type enable;




  typedef boost::shared_ptr< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> const> ConstPtr;

}; // struct ControlTorque_

typedef ::robotis_controller_msgs::ControlTorque_<std::allocator<void> > ControlTorque;

typedef boost::shared_ptr< ::robotis_controller_msgs::ControlTorque > ControlTorquePtr;
typedef boost::shared_ptr< ::robotis_controller_msgs::ControlTorque const> ControlTorqueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotis_controller_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'robotis_controller_msgs': ['/home/cat/robotnik_arm/src/ROBOTIS-Framework/robotis_controller_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6b11d561803e96cfa68e7be9c607e6d";
  }

  static const char* value(const ::robotis_controller_msgs::ControlTorque_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6b11d561803e96cULL;
  static const uint64_t static_value2 = 0xfa68e7be9c607e6dULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis_controller_msgs/ControlTorque";
  }

  static const char* value(const ::robotis_controller_msgs::ControlTorque_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n\
bool[] enable\n\
";
  }

  static const char* value(const ::robotis_controller_msgs::ControlTorque_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ControlTorque_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis_controller_msgs::ControlTorque_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis_controller_msgs::ControlTorque_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "enable[]" << std::endl;
    for (size_t i = 0; i < v.enable.size(); ++i)
    {
      s << indent << "  enable[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.enable[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_CONTROLTORQUE_H
