// Generated by gencpp from file robotis_controller_msgs/ControlWrite.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_CONTROLWRITE_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_CONTROLWRITE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis_controller_msgs
{
template <class ContainerAllocator>
struct ControlWrite_
{
  typedef ControlWrite_<ContainerAllocator> Type;

  ControlWrite_()
    : name()
    , addr(0)
    , length(0)
    , value(0)  {
    }
  ControlWrite_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , addr(0)
    , length(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint16_t _addr_type;
  _addr_type addr;

   typedef uint16_t _length_type;
  _length_type length;

   typedef uint32_t _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> const> ConstPtr;

}; // struct ControlWrite_

typedef ::robotis_controller_msgs::ControlWrite_<std::allocator<void> > ControlWrite;

typedef boost::shared_ptr< ::robotis_controller_msgs::ControlWrite > ControlWritePtr;
typedef boost::shared_ptr< ::robotis_controller_msgs::ControlWrite const> ControlWriteConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotis_controller_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'robotis_controller_msgs': ['/home/cat/robotnik_arm/src/ROBOTIS-Framework/robotis_controller_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f56d9435515b596a4742dbb69832f87e";
  }

  static const char* value(const ::robotis_controller_msgs::ControlWrite_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf56d9435515b596aULL;
  static const uint64_t static_value2 = 0x4742dbb69832f87eULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis_controller_msgs/ControlWrite";
  }

  static const char* value(const ::robotis_controller_msgs::ControlWrite_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
uint16 addr\n\
uint16 length\n\
uint32 value\n\
";
  }

  static const char* value(const ::robotis_controller_msgs::ControlWrite_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.addr);
      stream.next(m.length);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ControlWrite_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis_controller_msgs::ControlWrite_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis_controller_msgs::ControlWrite_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "addr: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.addr);
    s << indent << "length: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.length);
    s << indent << "value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_CONTROLWRITE_H
