// Generated by gencpp from file robotis_controller_msgs/PublishPosition.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_PUBLISHPOSITION_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_PUBLISHPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis_controller_msgs
{
template <class ContainerAllocator>
struct PublishPosition_
{
  typedef PublishPosition_<ContainerAllocator> Type;

  PublishPosition_()
    : name()
    , publish()  {
    }
  PublishPosition_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , publish(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _publish_type;
  _publish_type publish;




  typedef boost::shared_ptr< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> const> ConstPtr;

}; // struct PublishPosition_

typedef ::robotis_controller_msgs::PublishPosition_<std::allocator<void> > PublishPosition;

typedef boost::shared_ptr< ::robotis_controller_msgs::PublishPosition > PublishPositionPtr;
typedef boost::shared_ptr< ::robotis_controller_msgs::PublishPosition const> PublishPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotis_controller_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'robotis_controller_msgs': ['/home/cat/robotnik_arm/src/ROBOTIS-Framework/robotis_controller_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6907a80c1fcfefc01ef1bfaef7af05b";
  }

  static const char* value(const ::robotis_controller_msgs::PublishPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6907a80c1fcfefcULL;
  static const uint64_t static_value2 = 0x01ef1bfaef7af05bULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis_controller_msgs/PublishPosition";
  }

  static const char* value(const ::robotis_controller_msgs::PublishPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n\
bool[] publish\n\
";
  }

  static const char* value(const ::robotis_controller_msgs::PublishPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.publish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PublishPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis_controller_msgs::PublishPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis_controller_msgs::PublishPosition_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "publish[]" << std::endl;
    for (size_t i = 0; i < v.publish.size(); ++i)
    {
      s << indent << "  publish[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.publish[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_PUBLISHPOSITION_H
