// Generated by gencpp from file cat_move_to_target/GetJointValuesRequest.msg
// DO NOT EDIT!


#ifndef CAT_MOVE_TO_TARGET_MESSAGE_GETJOINTVALUESREQUEST_H
#define CAT_MOVE_TO_TARGET_MESSAGE_GETJOINTVALUESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cat_move_to_target
{
template <class ContainerAllocator>
struct GetJointValuesRequest_
{
  typedef GetJointValuesRequest_<ContainerAllocator> Type;

  GetJointValuesRequest_()
    : pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , zyx_angle_z(0.0)
    , zyx_angle_y(0.0)
    , zyx_angle_x(0.0)
    , hardcoded_wrist(false)  {
    }
  GetJointValuesRequest_(const ContainerAllocator& _alloc)
    : pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , zyx_angle_z(0.0)
    , zyx_angle_y(0.0)
    , zyx_angle_x(0.0)
    , hardcoded_wrist(false)  {
  (void)_alloc;
    }



   typedef double _pos_x_type;
  _pos_x_type pos_x;

   typedef double _pos_y_type;
  _pos_y_type pos_y;

   typedef double _pos_z_type;
  _pos_z_type pos_z;

   typedef double _zyx_angle_z_type;
  _zyx_angle_z_type zyx_angle_z;

   typedef double _zyx_angle_y_type;
  _zyx_angle_y_type zyx_angle_y;

   typedef double _zyx_angle_x_type;
  _zyx_angle_x_type zyx_angle_x;

   typedef uint8_t _hardcoded_wrist_type;
  _hardcoded_wrist_type hardcoded_wrist;




  typedef boost::shared_ptr< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetJointValuesRequest_

typedef ::cat_move_to_target::GetJointValuesRequest_<std::allocator<void> > GetJointValuesRequest;

typedef boost::shared_ptr< ::cat_move_to_target::GetJointValuesRequest > GetJointValuesRequestPtr;
typedef boost::shared_ptr< ::cat_move_to_target::GetJointValuesRequest const> GetJointValuesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cat_move_to_target

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "956284a21cdb84cf2ea6f34e4787d409";
  }

  static const char* value(const ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x956284a21cdb84cfULL;
  static const uint64_t static_value2 = 0x2ea6f34e4787d409ULL;
};

template<class ContainerAllocator>
struct DataType< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cat_move_to_target/GetJointValuesRequest";
  }

  static const char* value(const ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pos_x\n\
float64 pos_y\n\
float64 pos_z\n\
float64 zyx_angle_z\n\
float64 zyx_angle_y\n\
float64 zyx_angle_x\n\
bool hardcoded_wrist\n\
";
  }

  static const char* value(const ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_z);
      stream.next(m.zyx_angle_z);
      stream.next(m.zyx_angle_y);
      stream.next(m.zyx_angle_x);
      stream.next(m.hardcoded_wrist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetJointValuesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cat_move_to_target::GetJointValuesRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<double>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<double>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_z: ";
    Printer<double>::stream(s, indent + "  ", v.pos_z);
    s << indent << "zyx_angle_z: ";
    Printer<double>::stream(s, indent + "  ", v.zyx_angle_z);
    s << indent << "zyx_angle_y: ";
    Printer<double>::stream(s, indent + "  ", v.zyx_angle_y);
    s << indent << "zyx_angle_x: ";
    Printer<double>::stream(s, indent + "  ", v.zyx_angle_x);
    s << indent << "hardcoded_wrist: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hardcoded_wrist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAT_MOVE_TO_TARGET_MESSAGE_GETJOINTVALUESREQUEST_H
