// Generated by gencpp from file cat_move_to_target/GetJointValues.msg
// DO NOT EDIT!


#ifndef CAT_MOVE_TO_TARGET_MESSAGE_GETJOINTVALUES_H
#define CAT_MOVE_TO_TARGET_MESSAGE_GETJOINTVALUES_H

#include <ros/service_traits.h>


#include <cat_move_to_target/GetJointValuesRequest.h>
#include <cat_move_to_target/GetJointValuesResponse.h>


namespace cat_move_to_target
{

struct GetJointValues
{

typedef GetJointValuesRequest Request;
typedef GetJointValuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointValues
} // namespace cat_move_to_target


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cat_move_to_target::GetJointValues > {
  static const char* value()
  {
    return "7a5da121fb59cc8b0d5a404807350ade";
  }

  static const char* value(const ::cat_move_to_target::GetJointValues&) { return value(); }
};

template<>
struct DataType< ::cat_move_to_target::GetJointValues > {
  static const char* value()
  {
    return "cat_move_to_target/GetJointValues";
  }

  static const char* value(const ::cat_move_to_target::GetJointValues&) { return value(); }
};


// service_traits::MD5Sum< ::cat_move_to_target::GetJointValuesRequest> should match 
// service_traits::MD5Sum< ::cat_move_to_target::GetJointValues > 
template<>
struct MD5Sum< ::cat_move_to_target::GetJointValuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cat_move_to_target::GetJointValues >::value();
  }
  static const char* value(const ::cat_move_to_target::GetJointValuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cat_move_to_target::GetJointValuesRequest> should match 
// service_traits::DataType< ::cat_move_to_target::GetJointValues > 
template<>
struct DataType< ::cat_move_to_target::GetJointValuesRequest>
{
  static const char* value()
  {
    return DataType< ::cat_move_to_target::GetJointValues >::value();
  }
  static const char* value(const ::cat_move_to_target::GetJointValuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cat_move_to_target::GetJointValuesResponse> should match 
// service_traits::MD5Sum< ::cat_move_to_target::GetJointValues > 
template<>
struct MD5Sum< ::cat_move_to_target::GetJointValuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cat_move_to_target::GetJointValues >::value();
  }
  static const char* value(const ::cat_move_to_target::GetJointValuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cat_move_to_target::GetJointValuesResponse> should match 
// service_traits::DataType< ::cat_move_to_target::GetJointValues > 
template<>
struct DataType< ::cat_move_to_target::GetJointValuesResponse>
{
  static const char* value()
  {
    return DataType< ::cat_move_to_target::GetJointValues >::value();
  }
  static const char* value(const ::cat_move_to_target::GetJointValuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAT_MOVE_TO_TARGET_MESSAGE_GETJOINTVALUES_H
