// Generated by gencpp from file cat_move_to_target/GetTagPoseRequest.msg
// DO NOT EDIT!


#ifndef CAT_MOVE_TO_TARGET_MESSAGE_GETTAGPOSEREQUEST_H
#define CAT_MOVE_TO_TARGET_MESSAGE_GETTAGPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cat_move_to_target
{
template <class ContainerAllocator>
struct GetTagPoseRequest_
{
  typedef GetTagPoseRequest_<ContainerAllocator> Type;

  GetTagPoseRequest_()
    : tag_id(0)  {
    }
  GetTagPoseRequest_(const ContainerAllocator& _alloc)
    : tag_id(0)  {
  (void)_alloc;
    }



   typedef int16_t _tag_id_type;
  _tag_id_type tag_id;




  typedef boost::shared_ptr< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTagPoseRequest_

typedef ::cat_move_to_target::GetTagPoseRequest_<std::allocator<void> > GetTagPoseRequest;

typedef boost::shared_ptr< ::cat_move_to_target::GetTagPoseRequest > GetTagPoseRequestPtr;
typedef boost::shared_ptr< ::cat_move_to_target::GetTagPoseRequest const> GetTagPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cat_move_to_target

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ec977bed7560cbca3391cdd90f0db6c";
  }

  static const char* value(const ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ec977bed7560cbcULL;
  static const uint64_t static_value2 = 0xa3391cdd90f0db6cULL;
};

template<class ContainerAllocator>
struct DataType< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cat_move_to_target/GetTagPoseRequest";
  }

  static const char* value(const ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 tag_id\n\
";
  }

  static const char* value(const ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetTagPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cat_move_to_target::GetTagPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "tag_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.tag_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAT_MOVE_TO_TARGET_MESSAGE_GETTAGPOSEREQUEST_H
