// Generated by gencpp from file cat_move_to_target/GetTagPose.msg
// DO NOT EDIT!


#ifndef CAT_MOVE_TO_TARGET_MESSAGE_GETTAGPOSE_H
#define CAT_MOVE_TO_TARGET_MESSAGE_GETTAGPOSE_H

#include <ros/service_traits.h>


#include <cat_move_to_target/GetTagPoseRequest.h>
#include <cat_move_to_target/GetTagPoseResponse.h>


namespace cat_move_to_target
{

struct GetTagPose
{

typedef GetTagPoseRequest Request;
typedef GetTagPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTagPose
} // namespace cat_move_to_target


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cat_move_to_target::GetTagPose > {
  static const char* value()
  {
    return "9947cf06bd814875243bead8e5c2eb9e";
  }

  static const char* value(const ::cat_move_to_target::GetTagPose&) { return value(); }
};

template<>
struct DataType< ::cat_move_to_target::GetTagPose > {
  static const char* value()
  {
    return "cat_move_to_target/GetTagPose";
  }

  static const char* value(const ::cat_move_to_target::GetTagPose&) { return value(); }
};


// service_traits::MD5Sum< ::cat_move_to_target::GetTagPoseRequest> should match 
// service_traits::MD5Sum< ::cat_move_to_target::GetTagPose > 
template<>
struct MD5Sum< ::cat_move_to_target::GetTagPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cat_move_to_target::GetTagPose >::value();
  }
  static const char* value(const ::cat_move_to_target::GetTagPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cat_move_to_target::GetTagPoseRequest> should match 
// service_traits::DataType< ::cat_move_to_target::GetTagPose > 
template<>
struct DataType< ::cat_move_to_target::GetTagPoseRequest>
{
  static const char* value()
  {
    return DataType< ::cat_move_to_target::GetTagPose >::value();
  }
  static const char* value(const ::cat_move_to_target::GetTagPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cat_move_to_target::GetTagPoseResponse> should match 
// service_traits::MD5Sum< ::cat_move_to_target::GetTagPose > 
template<>
struct MD5Sum< ::cat_move_to_target::GetTagPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cat_move_to_target::GetTagPose >::value();
  }
  static const char* value(const ::cat_move_to_target::GetTagPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cat_move_to_target::GetTagPoseResponse> should match 
// service_traits::DataType< ::cat_move_to_target::GetTagPose > 
template<>
struct DataType< ::cat_move_to_target::GetTagPoseResponse>
{
  static const char* value()
  {
    return DataType< ::cat_move_to_target::GetTagPose >::value();
  }
  static const char* value(const ::cat_move_to_target::GetTagPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAT_MOVE_TO_TARGET_MESSAGE_GETTAGPOSE_H
