(cl:defpackage cat_move_to_target-srv
  (:use )
  (:export
   "GETJOINTVALUES"
   "<GETJOINTVALUES-REQUEST>"
   "GETJOINTVALUES-REQUEST"
   "<GETJOINTVALUES-RESPONSE>"
   "GETJOINTVALUES-RESPONSE"
   "GETTAGPOSE"
   "<GETTAGPOSE-REQUEST>"
   "GETTAGPOSE-REQUEST"
   "<GETTAGPOSE-RESPONSE>"
   "GETTAGPOSE-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

